name: Discv4 Crawl and DNS Update
on:
  schedule:
    - cron: '0 */4 * * *'
      
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'dominant-strategies/discv4-dns-lists'
    name: Discv4-DNS-Crawler
    runs-on: ubuntu-20.04
    env:
      QUAI_DNS_DISCV4_CRAWLTIME: 30m
      QUAI_DNS_DISCV4_PARENT_DOMAIN: quainodes.io
      QUAI_DNS_DISCV4_KEY_PATH: ./secrets/dnskey.json
      QUAI_DNS_DISCV4_KEYPASS_PATH: ./secrets/dnskey_password.txt
      QUAI_DNS_DISCV4_BOOTNODE: enode://84a1545d709e862e8ee45a87558e833b8fb1ba057a093fb7c974beb51e403b2c1d6f8a89404632804cf4ba1b47e3db9fcd629feb9fa90226fd2cf2b8ce83b0c9@104.198.48.112
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      QUAI_DNS_CLOUDFLARE_ZONEID: ${{ secrets.QUAI_DNS_CLOUDFLARE_ZONEID }}
      QUAI_DNS_DISCV4_KEY: ${{ secrets.QUAI_DNS_DISCV4_KEY }}
      QUAI_DNS_DISCV4_KEYPASS: ${{ secrets.QUAI_DNS_DISCV4_KEYPASS }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.8
      id: go

    - run: go version

    - run: sudo apt-get install -y jq

    - name: Check out code
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.PAT_REPO_USER }}

    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.PAT_REPO_USER }}
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --depth=1
        cd go-quai
        git fetch
        git fetch --tags
        # checkout_ref="$(git for-each-ref --count=1 --sort=-taggerdate --format '%(tag)' refs/tags)"
        # git checkout ${checkout_ref}
        checkout_ref="$(git for-each-ref --count=1 --sort=-committerdate --format '%(objectname)' refs/heads/master)"
        git checkout ${checkout_ref}
        touch network.env
        make go-quai
        echo "$(pwd)/build/bin" >> $GITHUB_PATH
        cd ..
        git diff --quiet || { git add go-quai && git -c user.name='alanorwick' -c user.email='alan.kev11@gmail.com' commit --author='crawler <>' -m "ci update (go-quai:${checkout_ref}) $GITHUB_RUN_ID:$GITHUB_RUN_NUMBER"; }

    - name: Setup secrets
      run: |
        mkdir secrets
        echo "$QUAI_DNS_DISCV4_KEY" > "$QUAI_DNS_DISCV4_KEY_PATH"
        echo "$QUAI_DNS_DISCV4_KEYPASS" > "$QUAI_DNS_DISCV4_KEYPASS_PATH"

    - name: Check env and secrets
      run: |
        ./.ci/deps.sh
        export QUAI_DNS_DISCV4_KEY_PUBLICINFO="$(cat $QUAI_DNS_DISCV4_KEYPASS_PATH | ethkey inspect $QUAI_DNS_DISCV4_KEY_PATH | grep -E '(Addr|Pub)')"
        echo "$QUAI_DNS_DISCV4_KEY_PUBLICINFO"

    - name: Condense Quai Nodes List
      run: |
        cat \
          all.mainnet.quainodes.io/nodes.json \
          all.ropsten.quainodes.io/nodes.json \
          | jq -s add \
          > all.json

    - name: Crawl
      run: |
        ./.ci/crawl.sh

    - name: Filter and sign
      run: |
        ./.ci/filter_and_sign.sh classic kotti mordor

    - name: Deploy to DNS
      run: |
        ./.ci/deploy.sh classic kotti mordor

    - name: Push
      env:
        GITHUB_PAT: ${{ secrets.PAT_REPO_USER }}
      run: |
        git config --local user.name 'alanorwick'
        git config --local user.email 'alan.kev11@gmail.com'
        git remote set-url origin https://alanorwick:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY}.git
        git push origin dominant-strategies